### ISSUE TITLE
The scroll of the code block

### ISSUE THREAD

**Issue by ykyouhei** [mittsuu/MarkedView-for-iOS#2]
@mittsuu Hi!
I would like to add the option to enable the scroll of the code block. ⛳

**Comment by mittsu333** [comment]
That sounds great idea!
Waiting for your pull request.

**Comment by mittsu333** [comment]
Hi, @ykyouhei  

The code scroll enable was added by v1.0.4 last.
Please try.

[Release Note v1.0.4](https://github.com/mittsuu/MarkedView-for-iOS/releases/tag/1.0.4)

**Comment by ykyouhei** [comment]
@mittsuu Hi!
very thanks! I try it!
